baseurl = "/"
theme = "coder"
title = "DJRaval"
[[menu.main]]
name = "About"
url = "/about/"
weight = 3
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[params]
author = "Devarshi Raval"
description = "Devarshi's personal website"
info = "Systems Engineer and FullStack Dev"
keywords = "Devarshi Raval,djraval,devarshi,cheatsec,ddit student,personal,website,ddu,14ituon057"
[[params.social]]
name = "Github"
url = "https://github.com/djraval/"
weight = 1
[[params.social]]
name = "Twitter"
url = "https://twitter.com/_djraval"
weight = 2
[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/djraval/"
weight = 3
